title: Dr. Kashif Naseer Qureshi # your name (or website title) here
logo: "/files/profile.jpg?raw=true" # your photo (or logo) here
description: >
 Abstract: <br>
 Hello, my name is Kashif, and I'm from <a href= "https://www.instagram.com/p/CClVytAF1oy/">  Limerick, Ireland.  </a>  
 I process medical images at <a href= "https://www.inaoep.mx/"> INAOE  </a> 
 and <a href= "https://maestriasydiplomados.tec.mx/escuelas/escuela-de-ingenieria-y-ciencias/"> Tecnológico de Monterrey  </a> <br> <br>
 
 Keywords: 
 
 Machine Learning, 
 Computer Vision 
 & Medical Image Analysis
 

theme: jekyll-theme-minimal
