title: Dr. Kashif Naseer Qureshi # your name (or website title) here
logo: "/files/profile.jpg?raw=true" # your photo (or logo) here
description: >
 Abstract: <br>
 Hello, my name is Dr. Kashif Naseer Qureshi, and I'm Associte Professor at <a href= "https://www.ul.ie/scieng/schools-and-departments/department-electronic-and-computer-engineering/dr-kashif-naseer.  </a>  
 My filed of study is Cyber Security at <a href= "https://www.cyberskills.ie/"> Cyber Skills  </a> 
 and Academic Advosr at <a href= "https://www.ccstuds.com/post/our-academic-and-industry-advisors-for-the-school-of-computing"> Bath Spa University, UAE </a> <br> <br>
 
 Keywords: 
 
 Cyber Security, 
 Computer Networks 
 & Wireless Communication
 

theme: jekyll-theme-minimal
